---
 - name: My first playbook
   hosts: webservers
   become: true
   tasks:
     - name: Install docker.io
       apt:
         name: docker.io
         state: present
     - name: Install python-pip
       apt:
         name: python-pip
         state: present

     - name: Install python docker
       pip:
         name: docker
         state: present

     - name: Download and launch a docker web container
       docker_container:
         name: dvwa
         image: cyberxsecurity/dvwa
         state: started
         published_ports: 80:80

